language: go
sudo: false
notifications:
  email: false
jobs:
  include:
    - go: 1.10.x
      stage: deploy
      go_import_path: github.com/xunchangguo/godep
      install: skip
      script: skip
      before_deploy:
        - chmod +x *.sh
        - ./dep.sh
      deploy:
        - provider: releases
          api_key:
            secure: "U5kRWK1q601SGrJAy5LhPynqjgf1/LNT+LisvbFVV6e7GcQj1fyA9YuOueVY39PNS0KjyU96CGKa9Gf6e/xBGnMHo3XKzmAtggyL/EuCcofWBnjnzjPMrX/z1RY8gC/o2CUdIoYianc0mw1WHjVCb/KScz9TnfxvYSA7Mj3z8/ezpzUpaRbuLm2W0QdVh5no6psrjgzc+pYfG5yovHXTdlOSsh3x+EsL2+wseS4U1C+2O6DEbQqu3ogsxnGI1o9hEqkZfmgTH10Ussx+InybFrZ+T4bufbyj+HJUgis3Dto5L3TcEQGow1UjVin6YabdZ+WiqZGeQM8KhRfSysGPoRLVI08GylYk+h4hXbuo2laxxuK/tLqTEWq5tz1jdbmGJGQ1Kv6bJU6t5/EbKDQDoF2QZxT3YcrgIqTiuZGVkCLBspmFu3lfj4r9Alvl5Ty+ZLMj+N5rKbE4hs9/z2ejBooEp1U7s9Gw8+20j1oRPFHs1SBE42vqNJisLvV3IWJ3GYlSQ3oqJHMt4Cia9Ah1oVxvTXuFtbDHV1xWKoF8MhJyxU7UO5pN9d9EFJ1cTAET8wAxNx5PY/5em4++HKTugeWQZNPLu35pd9lkw8CP3lyxEw9aIcJ6LSdhR2Ot0Oi4A5UNH0PajNt9wozOoctT2FBceerJO3PGSVBAuwdxDIo="
          file:
            - vendor.zip
          skip_cleanup: true
          on:
            repo: xunchangguo/godep
            branch: master
            tags: true
addons:
  ssh_known_hosts: github.com
